### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by smalleni** [SoftwareEngineeringToolDemos/ICSE-2014-Teamscale#7]
What is the password..tried teamscale didn't work..screen is locked after few minutes of inactivity and requires password to unlock.

**Comment by ppjena** [comment]
Hi,
I downloaded the vm. It didn't ask for any password so I am closing the
issue.

Regards,
Pragyan

**Comment by smalleni** [comment]
Please wait for us to arrive at a conclusion before closing the issue. If
you read the issue again, it says it asks for the password after several
minutes of inactivity. It would be wise to tag professor here and let him
say what he thinks of this. If I remember correctly, any password if there,
should be the name of the tool.
@CaptainEmerson

On Wed, Oct 21, 2015 at 1:26 PM, ppjena notifications@github.com wrote:

> Hi,
> I downloaded the vm. It didn't ask for any password so I am closing the
> issue.
> 
> Regards,
> Pragyan
> 
> On Wed, Oct 21, 2015 at 9:47 AM, Sai Sindhur Malleni <
> notifications@github.com> wrote:
> 
> > What is the password..tried teamscale didn't work..screen is locked after
> > few minutes of inactivity and requires password to unlock.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Teamscale/issues/7
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Teamscale/issues/7#issuecomment-149969080
> .

## 

Sai Sindhur Malleni
Performance Engineering Intern
Red Hat Inc.
100 East Davie Street
Raleigh, NC, USA
Work: (919) 890-8633 | Cell:(919) 985-1055

**Comment by ppjena** [comment]
Hi, I was inactive for 15-20 mins. Nothing happened. No password
requirement.

Thanks &Regards,
Pragyan

**Comment by ppjena** [comment]
Hi,
The password is vagrant. I changed it to nothing now in the VM. If you want
I can give you the latest .ova file.

Thanks &Regards,
Pragyan

**Comment by smalleni** [comment]
Should be fine.

On Wed, Oct 21, 2015 at 2:00 PM, ppjena notifications@github.com wrote:

> Hi,
> The password is vagrant. I changed it to nothing now in the VM. If you want
> I can give you the latest .ova file.
> 
> Thanks &Regards,
> Pragyan
> On Oct 21, 2015 1:29 PM, "Sai Sindhur Malleni" notifications@github.com
> wrote:
> 
> > Please wait for us to arrive at a conclusion before closing the issue. If
> > you read the issue again, it says it asks for the password after several
> > minutes of inactivity. It would be wise to tag professor here and let him
> > say what he thinks of this. If I remember correctly, any password if
> > there,
> > should be the name of the tool.
> > @CaptainEmerson
> > 
> > On Wed, Oct 21, 2015 at 1:26 PM, ppjena notifications@github.com
> > wrote:
> > 
> > > Hi,
> > > I downloaded the vm. It didn't ask for any password so I am closing the
> > > issue.
> > > 
> > > Regards,
> > > Pragyan
> > > 
> > > On Wed, Oct 21, 2015 at 9:47 AM, Sai Sindhur Malleni <
> > > notifications@github.com> wrote:
> > > 
> > > > What is the password..tried teamscale didn't work..screen is locked
> > > > after
> > > > few minutes of inactivity and requires password to unlock.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Teamscale/issues/7
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Teamscale/issues/7#issuecomment-149969080
> > 
> > > .
> > 
> > ## 
> > 
> > Sai Sindhur Malleni
> > Performance Engineering Intern
> > Red Hat Inc.
> > 100 East Davie Street
> > Raleigh, NC, USA
> > Work: (919) 890-8633 | Cell:(919) 985-1055
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Teamscale/issues/7#issuecomment-149970164
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Teamscale/issues/7#issuecomment-149978443
> .

## 

Sai Sindhur Malleni
Performance Engineering Intern
Red Hat Inc.
100 East Davie Street
Raleigh, NC, USA
Work: (919) 890-8633 | Cell:(919) 985-1055
